name: CI-Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Run test echo
        run: echo "Hello, GitHub Actions is working!"
